import test from "node:test";
import assert from "node:assert/strict";
import { DatabaseSync } from "node:sqlite";
import { readFileSync } from "node:fs";
import { cleanOptions, price, parseOutput, taskId, month, RESERVE_SQL } from "../lib/core";
import { buildGraph, validateGraph } from "../lib/workflow";
import visual from "../lib/source/28c.json";
const period="2026-10";
test("provider IDs retain all digits and reject already-rounded JSON numbers",()=>{assert.equal(taskId("2108613051860013058"),"2108613051860013058");assert.equal(taskId(2108613051860013058),null);assert.equal(taskId(undefined),null);assert.equal(taskId(12345678),"12345678");});
function database(){const db=new DatabaseSync(":memory:");db.exec(readFileSync("drizzle/0000_common_reavers.sql","utf8"));for(const id of ["alice","bob"])db.prepare("INSERT INTO accounts(id,email,name,active,budget,concurrent,created) VALUES(?,?,?,1,30,1,0)").run(id,`${id}@test.invalid`,id);return db;}
function reserve(db:DatabaseSync,id:string,owner:string,key:string,cost=20,globalLimit=2){return db.prepare(RESERVE_SQL).run(id,key,"image","test",cost,period,"{}",1,1,owner,cost,period,globalLimit);}
test("reservations enforce account concurrency, idempotency, global capacity and budget",()=>{
 const db=database();assert.equal(reserve(db,"a","alice","first").changes,1);assert.equal(reserve(db,"b","alice","first").changes,0);assert.equal(reserve(db,"c","alice","second").changes,0);
 assert.equal(reserve(db,"d","bob","first",20,1).changes,0);assert.equal(reserve(db,"d","bob","first").changes,1);
 db.prepare("UPDATE jobs SET state='SUCCESS' WHERE id='a'").run();assert.equal(reserve(db,"e","alice","second").changes,0);assert.equal(reserve(db,"f","alice","third",10).changes,1);assert.equal(db.prepare("SELECT SUM(cost) AS total FROM jobs WHERE owner='alice'").get()!.total,30);
});
test("uncertain submissions retain credit; repeated refund cannot add credit",()=>{const db=database();reserve(db,"a","alice","first");db.prepare("UPDATE jobs SET state='unknown' WHERE id='a'").run();assert.equal(reserve(db,"b","alice","second").changes,0);db.prepare("UPDATE jobs SET charged=0,state='refunded' WHERE id='a'").run();db.prepare("UPDATE jobs SET charged=0,state='refunded' WHERE id='a'").run();assert.equal(reserve(db,"b","alice","second").changes,1);assert.equal(db.prepare("SELECT SUM(cost) AS total FROM jobs WHERE owner='alice' AND charged=1").get()!.total,20);});
test("disabled accounts cannot reserve; tenant-scoped queries do not expose other jobs",()=>{const db=database();reserve(db,"a","alice","first");assert.equal(db.prepare("SELECT id FROM jobs WHERE id=? AND owner=?").get("a","bob"),undefined);db.prepare("UPDATE accounts SET active=0 WHERE id='bob'").run();assert.equal(reserve(db,"b","bob","first").changes,0);});
test("month boundary uses Sao Paulo and price is server-derived",()=>{assert.equal(month(new Date("2026-11-01T02:00:00Z")),"2026-10");assert.equal(month(new Date("2026-11-01T03:00:00Z")),"2026-11");assert.equal(price(cleanOptions({quality:"4K",head:true,tattoo:true,count:2}),10),100);assert.throws(()=>cleanOptions({count:999}));});
test("unknown API responses never become a fabricated success or automatic refund",()=>{assert.equal(parseOutput({code:804}).state,"RUNNING");assert.equal(parseOutput({code:813}).state,"QUEUED");assert.equal(parseOutput({code:999,data:[]}).state,"unconfirmed");assert.equal(parseOutput({code:0,data:[]}).state,"unconfirmed");assert.equal(parseOutput({code:0,data:[{fileUrl:"https://example.com/test.png",fileType:"png"}]}).state,"SUCCESS");});
// A structural fixture, NOT a runnable/exported API workflow. Real API validation remains pending.
function fixture(){const g:any={};for(const node of visual.nodes as any[]){if(node.type==="MarkdownNote")continue;const inputs:any={};for(const i of node.inputs||[]){if(i.link!=null){const l=(visual.links as any[]).find(l=>l[0]===i.link)!;inputs[i.name]=[String(l[1]),l[2]];}else inputs[i.name]=i.name==="prompt"?"fixture":1;}if(node.type==="LoadImage")inputs.image="fixture.png";g[String(node.id)]={class_type:node.type,inputs};}return g;}
test("visual JSON is rejected instead of silently treated as an API workflow",()=>{assert.throws(()=>validateGraph(visual),/formato API/);assert.throws(()=>validateGraph({}),/28C/);});
test("default graph removes optional references, tattoo generation, bypassed LoRA and upscale",()=>{const g=buildGraph(fixture(),{scene:"scene.png",front:"model.png"},"body_swap: test","","",cleanOptions({}));assert.equal(g["30"].inputs.image,"scene.png");assert.equal(g["19"].inputs.image,"model.png");for(const id of ["13","15","17","33","11","48","62","66"])assert.equal(g[id],undefined);assert.ok(g["41"]);assert.ok(g["52"]);assert.equal(g["32"].inputs["images.image_3"],undefined);});
test("head and mask disabled prune their costly branches",()=>{const g=buildGraph(fixture(),{scene:"scene.png",front:"model.png"},"body_swap: test","","",cleanOptions({head:false,mask:false}));for(const id of ["41","48","52","53","26"])assert.equal(g[id],undefined);assert.ok(g["35"]);});
test("optional view routes exactly the selected image and prevents missing upload",()=>{assert.throws(()=>buildGraph(fixture(),{scene:"s",front:"f"},"prompt","","",cleanOptions({view:"back"})),/referência/);const g=buildGraph(fixture(),{scene:"s",front:"f",back:"b"},"prompt","","",cleanOptions({view:"back"}));assert.deepEqual(g["32"].inputs["images.image_3"],["14",0]);assert.equal(g["13"].inputs.image,"b");assert.equal(g["15"],undefined);});
test("upscale and LoRA reconstruct supported nodes missing from an API export",()=>{const template=fixture();for(const id of ["11","13","14","62","63","64","65","66"])delete template[id];template["12"].inputs.model=["10",0];delete template["32"].inputs["images.image_3"];delete template["46"].inputs["images.image_3"];delete template["33"];for(const id of ["15","16","17","18"])delete template[id];const g=buildGraph(template,{scene:"s",front:"f",back:"b"},"prompt","","",cleanOptions({quality:"4K",bust:1,view:"back"}));assert.equal(g["64"].inputs.resolution,2160);assert.equal(g["65"].inputs.megapixels,8.3);assert.equal(g["11"].inputs.strength_model,1);assert.equal(g["13"].inputs.image,"b");});
