// Marketplace: os fluxos da agencia que a extensao oferece.
// Para pôr um fluxo novo: acrescente um item aqui (o arquivo tem de estar em ../../fluxos) e rode "npm run build",
// que copia os .json para extensao/fluxos. Capa opcional: extensao/capas/<id>.png, .webp ou .jpg.
//
// status: "aprovado" (rodou e o usuario aprovou), "testado" (rodou, com ajustes pendentes), "beta" (ainda nao rodou)
// selo: "TOP" (rosa) ou "NEW" (limao) no canto do card
// prompt: o id da ferramenta da extensao que escreve os prompts deste fluxo (modos.js), ou null

export const CATEGORIAS = ["Todos", "Modelo", "Edição", "Vídeo", "Teste"];

export const CATALOGO = [
  {
    id: "oito-vistas-27",
    nome: "Oito vistas da modelo",
    resumo: "Do corpo aprovado para 4 corpos e 4 bustos com a mesma tatuagem.",
    capa: "8 VISTAS",
    cor: "#3b4a00",
    categoria: "Modelo",
    status: "aprovado",
    selo: "TOP",
    destaque: true,
    modelo: "Qwen-Image-Edit 2511 + LoRA de ângulos da fal · SeedVR2 · Qwen-Image-2.1",
    licenca: "Qwen 2511 livre; Qwen 2.1 (upscale dos bustos) só pesquisa",
    descricao:
      "Os corpos de lado e de costas giram com a LoRA Multiple-Angles da fal; o lado esquerdo sai pelo espelho ida e volta, com a manga floral no braço certo. Os 4 bustos são recortes dos corpos da mesma vista, ampliados pelo SeedVR2 e terminados no Qwen 2.1 com o Detail Enhancer. Sai uma folha final com as 8.",
    entradas: ["CORPO INTEIRO APROVADO (o resultado do passo 02)"],
    subir: ["elusarcas-qwen2-1-detailer-v1.safetensors (Civitai 2956730, 77,9 MB)"],
    passos: [
      "Gere os textos na ferramenta Oito vistas e cole nos nós indicados.",
      "Suba o corpo aprovado no nó CORPO INTEIRO APROVADO.",
      "Rode e use a FOLHA FINAL. Recorte: largura 0.64, altura 0.40; denoise do upscale 0.6.",
    ],
    arquivos: [["27 etapa 2 (fal)", "27_etapa2_vistas_qwen2511_fal.json"]],
    prompt: "vistas",
  },
  {
    id: "corpo-inteiro-27",
    nome: "Corpo inteiro tatuado",
    resumo: "Rosto + foto do corpo + mangas viram o corpo inteiro de frente.",
    capa: "CORPO + TATTOO",
    cor: "#4a1030",
    categoria: "Modelo",
    status: "aprovado",
    selo: "NEW",
    destaque: true,
    modelo: "Qwen-Image-2.1 · Lenovo UltraReal 2.1 · Breasts Slider 2.1 · refino Z-Image · troca de cabeça BFS (Qwen 2511)",
    licenca: "Qwen 2.1 só pesquisa",
    descricao:
      "A foto do corpo dá só o formato e as proporções; o rosto, o cabelo e o tom de pele vêm do rosto aprovado; cada manga vem da sua foto, tatuada como tinta cicatrizada, sem branco. Biquíni e negativo contra nudez em todo prompt. Refino de pele com Z-Image + Realistic Snapshot.",
    entradas: ["FOTO DO CORPO (só formato)", "ROSTO DA MODELO", "MANGA DO BRAÇO DIREITO", "MANGA DO BRAÇO ESQUERDO"],
    subir: ["lenovo_qwen21.safetensors (Civitai 1662740)", "breasts_slider_qwen-inage2.1_v1.safetensors (Civitai 764250)"],
    passos: [
      "Gere os 6 textos na ferramenta Corpo inteiro e cole nos nós indicados.",
      "Suba as 4 imagens nos nós verdes.",
      "Rode até aprovar o corpo: tatuagem errada aqui passa para todas as vistas.",
      "Use o RESULTADO FINAL do grupo 4: ele troca a cabeça pela do rosto de referência (BFS Head no Qwen 2511).",
    ],
    arquivos: [["27 etapa 1", "27_etapa1_corpo_inteiro_qwen21.json"]],
    prompt: "corpo",
  },
  {
    id: "corpo-sem-tatuagem-27",
    nome: "Corpo inteiro sem tatuagem",
    resumo: "Rosto + foto do corpo viram o corpo inteiro de frente, pele limpa.",
    capa: "CORPO CLEAN",
    cor: "#203a4a",
    categoria: "Modelo",
    status: "beta",
    selo: "NEW",
    destaque: false,
    modelo: "Qwen-Image-2.1 · Lenovo UltraReal 2.1 · Breasts Slider 2.1 · refino Z-Image · troca de cabeça BFS (Qwen 2511)",
    licenca: "Qwen 2.1 só pesquisa",
    descricao:
      "O mesmo fluxo aprovado do corpo inteiro, para modelo sem tatuagens: a foto do corpo dá só o formato e as proporções; rosto, cabelo, tom de pele e piercings do rosto vêm do rosto aprovado. O negativo segura nudez e tatuagens da foto do corpo; o texto comum nunca fala de tatuagem, porque o refino desenha o que estiver escrito.",
    entradas: ["FOTO DO CORPO (só formato)", "ROSTO DA MODELO"],
    subir: ["lenovo_qwen21.safetensors (Civitai 1662740)", "breasts_slider_qwen-inage2.1_v1.safetensors (Civitai 764250)"],
    passos: [
      "Gere os 4 textos na ferramenta Corpo inteiro > Sem tatuagens e cole nos nós indicados.",
      "Suba a foto do corpo e o rosto nos nós verdes.",
      "Rode até aprovar o corpo; confira se nenhuma tatuagem da foto do corpo passou.",
      "Use o RESULTADO FINAL do grupo 4: ele troca a cabeça pela do rosto de referência (BFS Head no Qwen 2511).",
    ],
    arquivos: [["27 etapa 1 sem tatuagem", "27_etapa1_corpo_inteiro_sem_tatuagem_qwen21.json"]],
    prompt: "corpo_sem",
  },
  {
    id: "rosto-teste-pele",
    nome: "Rosto realista",
    resumo: "O mesmo rosto em várias LoRAs de pele, lado a lado.",
    capa: "ROSTO · PELE",
    cor: "#2a2f36",
    categoria: "Teste",
    status: "beta",
    selo: null,
    destaque: true,
    modelo: "Z-Image Turbo · Krea 2 Turbo · Flux.2 Klein 9B",
    licenca: "Z-Image livre; Krea 2 livre até US$ 1 mi/ano; Klein 9B não comercial",
    descricao:
      "Cada fluxo gera a mesma foto (mesmo prompt, mesma seed) várias vezes: o ramo A sem LoRA e um ramo por LoRA de pele. A seed muda a cada rodada, então rodar de novo dá outro rosto. O 24D roda os três modelos juntos (Z-Image, Krea 2 e Klein 9B), com o modelo puro e uma LoRA de pele ligados em cada um, e devolve uma folha para comparar.",
    entradas: ["PROMPT DO TESTE (gerado na ferramenta Rosto)", "NEGATIVO (só vale com o nó NAG ligado)", "SEED (muda a cada rodada)"],
    subir: ["As LoRAs de cada ramo estão no LEIA de entrega_24_teste_pele (Realistic Snapshot, Lenovo, UltraReal...)"],
    passos: [
      "Gere o prompt na ferramenta Rosto e cole no nó PROMPT DO TESTE (no 24D ele vale para os três modelos).",
      "Rode e compare os ramos. Aprove um rosto de frente, fundo branco.",
    ],
    arquivos: [
      ["24D os 3 juntos", "24D_rosto_3_modelos.json"],
      ["24A Z-Image", "24A_teste_pele_zimage_turbo.json"],
      ["24B Krea 2", "24B_teste_pele_krea2.json"],
      ["24C Klein 9B", "24C_teste_pele_klein9b.json"],
    ],
    prompt: "rosto",
  },
  {
    id: "body-swap-28",
    nome: "Body swap",
    resumo: "Coloca a nossa modelo no lugar da pessoa de qualquer foto de cena.",
    capa: "BODY SWAP",
    cor: "#4a3a10",
    categoria: "Edição",
    status: "aprovado",
    selo: null,
    destaque: false,
    modelo: "Qwen-Image-2.1 · Pruna 8 passos · BFS Head v1.1 (2.1)",
    licenca: "Qwen 2.1 só pesquisa",
    descricao:
      "O fluxo de body swap da agência: a foto da cena é a <image1> e a modelo é a <image2>. O prompt body_swap de 13 parágrafos (ferramenta Body swap) vai no encoder; saída em 2 MP, 8 passos com a LoRA Pruna e a BFS Head do Qwen 2.1. Os Set/Get do KJNodes viraram ligações diretas para rodar também no RunningHub.",
    entradas: ["Body Reference: a foto da cena (<image1>)", "Head Reference: a nossa modelo (<image2>)", "PROMPT body_swap (ferramenta Body swap)"],
    subir: ["bfs_head_v1.1_qwen_2.1.safetensors (BFS Head para Qwen 2.1)", "p_qwen_image_2.1_8step_v0.1.safetensors (PrunaAI)"],
    passos: [
      "Gere o prompt na ferramenta Body swap com as mesmas duas fotos.",
      "Suba a cena no Body Reference e a modelo no Head Reference.",
      "Cole o prompt no nó PROMPT body_swap e rode. O sampler deis_2m é do pacote RES4LYF.",
    ],
    arquivos: [["28 body swap", "28_body_swap_qwen21.json"]],
    prompt: "swap",
  },
  {
    id: "troca-roupa-29",
    nome: "Troca de roupa",
    resumo: "Até 5 roupas e acessórios vestidos na sua foto.",
    capa: "OUTFIT",
    cor: "#3a104a",
    categoria: "Edição",
    status: "beta",
    selo: "NEW",
    destaque: true,
    modelo: "Qwen-Image-2.1 · Pruna 8 passos (a mesma base do body swap)",
    licenca: "Qwen 2.1 só pesquisa",
    descricao:
      "Feito a partir do body swap: a sua foto é a <image1> e cada roupa ou acessório entra numa imagem, da <image2> à <image6>. O pedido diz de que imagem vem cada peça, como usar e o que da roupa atual fica. Saída em 2 MP, no formato da sua foto, com antes e depois.",
    entradas: ["SUA FOTO (<image1>)", "ROUPA/ACESSÓRIO 1 a 5 (<image2> a <image6>)", "PEDIDO (ferramenta Troca de roupa)"],
    subir: ["p_qwen_image_2.1_8step_v0.1.safetensors (PrunaAI), a mesma do body swap"],
    passos: [
      "Gere o pedido na ferramenta Troca de roupa com as mesmas fotos.",
      "Suba a sua foto e as roupas. Ligue (Ctrl+M) os grupos ROUPA 2 a 5 que usar, em ordem.",
      "Cole o pedido no nó PEDIDO e rode.",
    ],
    arquivos: [["29 troca de roupa", "29_troca_de_roupa_qwen21.json"]],
    prompt: "roupa",
  },
  {
    id: "edicao-maxima-21",
    nome: "Edição máxima Qwen 2.1",
    resumo: "Edite qualquer foto pedindo em português, até 4 MP.",
    capa: "EDIÇÃO 2K",
    cor: "#123a4a",
    categoria: "Edição",
    status: "beta",
    selo: null,
    destaque: false,
    modelo: "Qwen-Image-2.1 com o reescritor oficial",
    licenca: "Qwen 2.1 só pesquisa",
    descricao:
      "O reescritor oficial da Qwen lê a foto e escreve o pedido em inglês. 40 passos, CFG só no começo, saída até 2048x2048, e uma segunda saída com a cor casada com a original.",
    entradas: ["FOTO (a <image1>)", "PEDIDO (pode ser em português)"],
    subir: [],
    passos: ["Suba a foto no nó FOTO.", "Escreva o pedido no nó PEDIDO.", "Rode: saem resultado, resultado_cor_original e antes_depois."],
    arquivos: [["21 Edição máxima", "21_qwen21_edicao_maxima.json"]],
    prompt: null,
  },
  {
    id: "copiar-movimento-22",
    nome: "Copiar movimento (H3)",
    resumo: "A modelo repete os passos e gestos de um vídeo.",
    capa: "MOTION",
    cor: "#3a1f4a",
    categoria: "Vídeo",
    status: "beta",
    selo: null,
    destaque: false,
    modelo: "MiniMax H3 Ref2VA · SDPose · ControlNet-Union",
    licenca: "MiniMax H3",
    descricao:
      "O vídeo vira esqueleto (SDPose) e entra pelo ControlNet-Union do H3; a identidade vem das fotos ROSTO e CORPO. Você escreve o pedido em português e o próprio H3 reescreve no formato oficial de seis seções.",
    entradas: ["VIDEO DO MOVIMENTO (até 14 s)", "ROSTO (<Picture 1>)", "CORPO (<Picture 2>)", "PEDIDO em português"],
    subir: [],
    passos: ["Suba o vídeo, o rosto e o corpo.", "Escreva o pedido.", "Confira a prévia do esqueleto antes da parte cara."],
    arquivos: [["22 Copiar movimento", "22_h3_copiar_movimento.json"]],
    prompt: null,
  },
  {
    id: "troca-cenario-21",
    nome: "Trocar cenário (foto)",
    resumo: "A modelo num lugar novo: ela fica igual, mudam o fundo e a luz.",
    capa: "CENÁRIO",
    cor: "#0f3a3a",
    categoria: "Edição",
    status: "beta",
    selo: "NEW",
    destaque: true,
    modelo: "Qwen-Image-2.1 edição máxima (fluxo 21)",
    licenca: "Qwen 2.1 só pesquisa",
    descricao:
      "Usa o fluxo 21: a foto da modelo em <image1> e, se quiser, a foto do lugar em <image2>. O pedido sai da extensão travando rosto, corpo, pose, roupa e tatuagens e pedindo luz, sombra e perspectiva do lugar novo.",
    entradas: ["FOTO (a modelo)", "REF 1 (a foto do lugar, opcional)", "PEDIDO (ferramenta Trocar cenário)"],
    subir: [],
    passos: [
      "Abra o fluxo no RunningHub (Abrir no RunningHub).",
      "Na ferramenta Trocar cenário, ponha a foto e (se tiver) o lugar, descreva o cenário e gere o pedido.",
      "Aplicar no fluxo aberto: sobem as fotos, o pedido entra e o reescritor fica desligado.",
      "Para vídeo: faça em 9:16 e de corpo inteiro e use o resultado em Trocar cenário no vídeo.",
    ],
    arquivos: [["21 edição máxima", "21_qwen21_edicao_maxima.json"]],
    prompt: "cenario",
  },
  {
    id: "troca-cenario-video-31",
    nome: "Trocar cenário no vídeo (SCAIL2)",
    resumo: "O vídeo com o cenário da foto e o movimento do vídeo original.",
    capa: "CENÁRIO VÍDEO",
    cor: "#102a3a",
    categoria: "Vídeo",
    status: "beta",
    selo: "NEW",
    destaque: false,
    modelo: "Wan 2.1 SCAIL2 14B (modo animação) · lightx2v · SAM3 · GIMM-VFI",
    licenca: "Wan 2.1 (Apache 2.0) · SAM3 (Meta)",
    descricao:
      "O 30 em modo animação: em vez de trocar a pessoa e manter o lugar do vídeo, anima a foto da modelo no cenário novo com o movimento do vídeo. O vídeo sai com o cenário da foto, até ~30 s, a 32 fps com o áudio original.",
    entradas: ["VIDEO DE ORIGEM (só o movimento)", "FOTO DA MODELO NO CENARIO NOVO", "DESCRICAO DA CENA", "PESSOAS NO VIDEO", "MODO (false)"],
    subir: [],
    passos: [
      "Faça a foto da modelo no cenário novo em Trocar cenário (9:16, corpo inteiro, pose parecida com o começo do vídeo).",
      "Abra este fluxo no RunningHub.",
      "Na ferramenta Trocar cenário no vídeo, ponha essa foto e o vídeo e clique em Aplicar no fluxo aberto.",
      "Comece com 5 a 10 segundos.",
    ],
    arquivos: [["31 SCAIL2 cenário", "31_troca_cenario_video_scail2.json"]],
    prompt: "cenario_video",
  },
  {
    id: "troca-video-scail2-30",
    nome: "Troca de personagem no vídeo (SCAIL2)",
    resumo: "A modelo no lugar da pessoa do vídeo, com o mesmo movimento.",
    capa: "SCAIL2",
    cor: "#3a1030",
    categoria: "Vídeo",
    status: "beta",
    selo: "NEW",
    destaque: true,
    modelo: "Wan 2.1 SCAIL2 14B fp8 · LoRA lightx2v · SAM3 · GIMM-VFI",
    licenca: "Wan 2.1 (Apache 2.0) · SAM3 (Meta)",
    descricao:
      "O SAM3 segue a pessoa do vídeo e a da foto, o Wan 2.1 SCAIL2 refaz o vídeo com a nossa modelo no lugar, um loop estende o vídeo em blocos de 73 frames (até ~30 s) e o GIMM-VFI dobra para 32 fps, com o áudio do vídeo original.",
    entradas: ["VIDEO DE ORIGEM", "FOTO DA MODELO", "DESCRICAO DA CENA", "PESSOAS NO VIDEO"],
    subir: [],
    passos: [
      "Abra o fluxo no RunningHub (Abrir no RunningHub).",
      "Na ferramenta Troca no vídeo, ponha a foto da modelo e o vídeo e clique em Aplicar no fluxo aberto: os dois sobem direto.",
      "Comece com 5 a 10 segundos: vídeo mais longo custa mais.",
      "Rode. O RESULTADO sai a 32 fps com o áudio original.",
    ],
    arquivos: [["30 SCAIL2", "30_troca_personagem_video_scail2.json"]],
    prompt: "video_scail",
  },
  {
    id: "body-swap-lote-28b",
    nome: "Body swap em lote (até 10 fotos)",
    resumo: "A mesma modelo em até 10 cenas, numa execução só.",
    capa: "SWAP ×10",
    cor: "#3a2a10",
    categoria: "Edição",
    status: "beta",
    selo: "NEW",
    destaque: false,
    modelo: "Qwen-Image-2.1 int8 · Pruna 8 passos · BFS Head v1.1 · QwenImage21Cache · Breasts Slider 2.1 (opcional)",
    licenca: "Qwen-Image-2.1: só pesquisa (a mesma do body swap 28)",
    descricao:
      "O body swap do fluxo 28 repetido em 10 trilhos. A modelo e os modelos de IA são carregados uma vez; cada trilho tem a foto da cena, o prompt body_swap escrito para ela e o resultado. Só rodam os trilhos ligados, e um não depende do outro. Em 2K ou 4K, cada foto passa pelo seu próprio upscale SeedVR2 (grupos UPSCALE NN), com os modelos do upscale carregados uma vez. A modelo pode ir em 4 fotos (frente, costas, esquerda, direita): a de frente é sempre a <image2>, e cada cena recebe como <image3> a foto que mais casa com ela, citada no prompt, para as tatuagens saírem fiéis. A LoRA do busto do Corpo inteiro (Breasts Slider 2.1) fica na cadeia do modelo, desligada até ligar. Etapa 2 (ligada ao abrir): depois do corpo, cada foto passa por uma troca de cabeça com a BFS Head e o gatilho head_swap:, com o close da modelo como <image2>, para o rosto ficar mais fiel e a expressão da cena voltar. Saem as duas versões: ETAPA 1 (só o corpo) e RESULTADO. Etapa 3 (experimental, desligada ao abrir): uma passada só para corrigir as tatuagens, com uma cópia de antes para comparar. MÁSCARA (ligada ao abrir): o SAM3 acha a pessoa na cena e a modelo no resultado, e só ela é colada de volta sobre a foto original; o resto sai igual, pixel por pixel. Sai também o SEM MASCARA de cada foto.",
    entradas: ["Head Reference (a modelo de frente)", "MODELO COSTAS, ESQUERDA e DIREITA (opcionais)", "MODELO ROSTO (close da modelo; sem close, a de frente)", "ETAPA 2 (troca de cabeça)", "CABECA 01 a 10 (o head_swap de cada foto)", "ETAPA 3 e TATUAGENS 01 a 10 (reforço das tatuagens, experimental)", "MASCARA e COR (só a modelo muda; ajuste de cor opcional)", "VISTA 01 a 10 (qual foto extra vai como <image3>)", "CENA 01 a 10", "PROMPT 01 a 10", "QUALIDADE", "VERSOES POR FOTO", "UPSCALE FINAL e UPSCALE 01 a 10 (2K e 4K)", "LoRA Breasts Slider 2.1"],
    subir: ["breasts_slider_qwen-inage2.1_v1.safetensors (Civitai 764250), só para ligar a LoRA do busto; é a mesma do fluxo 27"],
    passos: [
      "Abra o fluxo no RunningHub (Abrir no RunningHub).",
      "Na ferramenta Body swap em lote, ponha a modelo de frente (e, se tiver, de costas, esquerda e direita) e as fotos de cena, e gere os prompts.",
      "Cada prompt mostra qual foto da modelo usa: só a frente, ou frente + a que mais casa com a cena (<image3>).",
      "No campo Busto, escolha o peso da LoRA Breasts Slider ou desligue.",
      "Etapa 2: ponha um close do rosto da modelo no quadro rosto (opcional) e deixe a Etapa 2 ligada. Cada prompt ganha um parágrafo head_swap: que descreve a expressão da cena; com ela, cada foto leva duas gerações.",
      "Clique em Aplicar no fluxo aberto: as fotos sobem, cada prompt entra no trilho dele e só ligam os trilhos com foto.",
      "Em Formato e qualidade, 2K ou 4K liga o upscale de cada foto do lote; 1080p ou menos desliga.",
      "Teste com 2 ou 3 fotos em 2K antes de mandar as 10: cada foto é um body swap inteiro e o upscale é a parte mais lenta.",
    ],
    arquivos: [["28B body swap em lote", "28B_body_swap_lote_qwen21.json"]],
    prompt: "swap_lote",
  },
  {
    id: "ugc-produto-h3-32",
    nome: "Vídeo UGC com produto (H3)",
    resumo: "A modelo fala do produto para a câmera, com voz e som.",
    capa: "UGC",
    cor: "#123a2a",
    categoria: "Vídeo",
    status: "beta",
    selo: "NEW",
    destaque: true,
    modelo: "MiniMax H3 Ref2VA · Qwen3-VL 32B · turbo de 8 passos · LoRAs de realismo opcionais",
    licenca: "MiniMax H3 Community License: avise que o vídeo é feito por IA; confira as regras de uso comercial",
    descricao:
      "O H3 recebe só fotos de referência, na ordem: o rosto e o corpo da modelo, o produto e até 3 extras (outro ângulo, embalagem, lugar). O pedido diz a cena, o que ela faz com o produto e a fala em português, e o H3 gera a imagem, a voz e o som de uma vez, em até 14 segundos. Opcionais desligados: primeiro quadro pronto, áudio com a voz dela e duas LoRAs de realismo.",
    entradas: ["ROSTO", "CORPO", "PRODUTO", "REF 4 a 6 (opcionais)", "PEDIDO", "DURACAO", "FORMATO"],
    subir: ["h3-realism-people-t2v-i2v-r2v.safetensors (só para usar a LoRA Realism People; 125 MB, huggingface.co/fal/MiniMax-H3-Realism-People-LoRA)"],
    passos: [
      "Abra o fluxo no RunningHub (Abrir no RunningHub).",
      "Na ferramenta Vídeo UGC com produto, ponha o rosto, o corpo e o produto, diga o produto e a fala e gere o pedido.",
      "Clique em Aplicar no fluxo aberto: as fotos sobem e o pedido entra pronto.",
      "Comece na rodada Teste, com 5 a 8 segundos. Gostou da cena? Rode a Final.",
    ],
    arquivos: [["32 UGC com produto", "32_ugc_produto_h3.json"]],
    prompt: "ugc",
  },
  {
    id: "react-h3-33",
    nome: "Vídeo de react (H3)",
    resumo: "Ela assiste alguma coisa e reage para a câmera, com som.",
    capa: "REACT",
    cor: "#2a1a3a",
    categoria: "Vídeo",
    status: "beta",
    selo: "NEW",
    destaque: true,
    modelo: "MiniMax H3 Ref2VA · Qwen3-VL 32B · turbo de 8 passos · LoRAs opcionais",
    licenca: "MiniMax H3 Community License: avise que o vídeo é feito por IA; confira as regras de uso comercial",
    descricao:
      "Só ela, assistindo a uma tela e reagindo; o que ela assiste entra depois, na edição. A foto dela já no lugar entra como referência (o H3 monta a cena a partir dela) ou, pela chave PRIMEIRO QUADRO, como o quadro em que o vídeo começa. Para ela falar sempre com a mesma voz, o áudio exato da fala sobe e entra no vídeo do jeito que está. Três estilos (streamer, celular, igual à foto), quatro reações, até 14 segundos, turbo para testar. Opcionais desligados: rosto em close e três LoRAs.",
    entradas: ["FOTO (referência ou primeiro quadro)", "PRIMEIRO QUADRO (chave)", "ROSTO EM CLOSE (opcional)", "FALA (áudio, opcional)", "PEDIDO", "DURACAO", "FORMATO"],
    subir: ["h3-realism-people-t2v-i2v-r2v.safetensors (só para a LoRA Realism People)", "minimax-h3-facial-realism-closeup-cp2000.safetensors (só para a LoRA Expressão do rosto; 71 MB, huggingface.co/prithivMLmods/MiniMax-H3-Facial-Realism-CloseUp)"],
    passos: [
      "Abra o fluxo no RunningHub (Abrir no RunningHub).",
      "Na ferramenta Vídeo de react, ponha a foto dela já no lugar, escolha o estilo e a reação e diga o que ela assiste.",
      "Para ela falar: grave a frase, suba o áudio e escreva as palavras exatas. Para só assistir: deixe sem áudio.",
      "Clique em Aplicar no fluxo aberto. Comece na rodada Teste; gostou? Rode a Final.",
    ],
    arquivos: [["33 vídeo de react", "33_react_h3.json"]],
    prompt: "react",
  },
  {
    id: "troca-video-23",
    nome: "Trocar pessoa no vídeo (H3)",
    resumo: "Troca a mulher de um vídeo pela modelo, mantendo o fundo.",
    capa: "SWAP VÍDEO",
    cor: "#4a2a10",
    categoria: "Vídeo",
    status: "beta",
    selo: null,
    destaque: false,
    modelo: "MiniMax H3 Ref2VA turbo 8 passos · SAM3",
    licenca: "MiniMax H3",
    descricao:
      "Versão 2 do miniMaxCharacterReplace: SAM3 acha a pessoa, o rosto original é borrado na referência, o H3 refaz só a pessoa e o resultado é colado de volta no vídeo original.",
    entradas: ["VIDEO_ORIGINAL", "MODELO (foto da modelo)"],
    subir: [],
    passos: ["Suba o vídeo e a foto da modelo.", "Rode. Se sobrar sombra na parede, o próximo passo é o modo inpaint."],
    arquivos: [["23 Troca H3 v2", "23_h3_troca_modelo_v2.json"]],
    prompt: null,
  },
  {
    id: "oito-vistas-rosto-25",
    nome: "Oito vistas a partir do rosto",
    resumo: "Do close do rosto para 8 vistas em fundo branco, sem tatuagem.",
    capa: "TURNAROUND",
    cor: "#1f3a2a",
    categoria: "Modelo",
    status: "testado",
    selo: null,
    destaque: false,
    modelo: "Qwen 2511 + fal (25A) · Krea 2 + Identity Edit (25B) · Klein 9B (25C)",
    licenca: "25A livre; 25B livre até US$ 1 mi/ano; 25C não comercial",
    descricao:
      "Três versões da mesma corrente para comparar: corpo inteiro e busto de frente, lado direito, costas e lado esquerdo, com refino de pele Z-Image. Para modelo sem tatuagem; com tatuagem, use o processo Corpo inteiro + Oito vistas.",
    entradas: ["ROSTO DA MODELO (close, fundo branco)", "COMO ELA É (cabelo e corpo)"],
    subir: ["RealisticSnapshot-Zimage-Turbov5.safetensors (refino)"],
    passos: ["Suba o close do rosto.", "Edite COMO ELA É.", "Rode e use a folha refinada."],
    arquivos: [
      ["25A Qwen 2511", "25A_vistas_qwen2511.json"],
      ["25B Krea 2", "25B_vistas_krea2.json"],
      ["25C Klein 9B", "25C_vistas_klein9b.json"],
    ],
    prompt: null,
  },
];

export const STATUS = {
  aprovado: { rotulo: "Aprovado", classe: "aprovado" },
  testado: { rotulo: "Testado", classe: "testado" },
  beta: { rotulo: "Beta · não testado", classe: "beta" },
};
